import { z, ZodSchema } from 'zod';

/**
 * WeakMap cache for converted and sanitized Gemini JSON schemas.
 * Keyed by original Zod schema object reference to ensure garbage collection.
 */
const schemaCache = new WeakMap<ZodSchema<any>, Record<string, any>>();

/**
 * Keywords in standard JSON Schema that are unsupported by Gemini's OpenAPI schema dialect
 * and must be removed to avoid API rejection.
 */
const UNSUPPORTED_KEYWORDS = new Set([
  '$schema',
  'minLength',
  'maxLength',
  'minItems',
  'maxItems',
  'additionalProperties',
]);

/**
 * Recursively sanitizes a JSON Schema object for compatibility with Google Gemini OpenAPI schema requirements.
 *
 * Transformations (per EXP-02):
 * 1. Strips top-level $schema header and unsupported validation keywords (minLength, maxLength, minItems, maxItems, additionalProperties).
 * 2. Normalizes nullable union type arrays (e.g., type: ["string", "null"]) into { type: "string", nullable: true }.
 * 3. Recursively processes nested object properties, items, definitions, and anyOf/oneOf/allOf arrays.
 *
 * @param schema The raw JSON Schema object generated by z.toJSONSchema().
 * @returns A sanitized, Gemini-compatible OpenAPI schema copy.
 */
export function sanitizeSchemaForGemini(schema: Record<string, any>): Record<string, any> {
  if (typeof schema !== 'object' || schema === null) {
    return schema;
  }

  if (Array.isArray(schema)) {
    return schema.map((item) => sanitizeSchemaForGemini(item));
  }

  const result: Record<string, any> = {};

  for (const [key, value] of Object.entries(schema)) {
    // 1. Omit unsupported keywords per EXP-02 finding
    if (UNSUPPORTED_KEYWORDS.has(key)) {
      continue;
    }

    // 2. Handle type: ["someType", "null"] array normalization
    if (key === 'type' && Array.isArray(value)) {
      const nonNullTypes = value.filter((t) => t !== 'null');
      const isNullable = value.includes('null');

      if (nonNullTypes.length === 1) {
        result.type = nonNullTypes[0];
        if (isNullable) {
          result.nullable = true;
        }
      } else {
        result.type = nonNullTypes;
        if (isNullable) {
          result.nullable = true;
        }
      }
      continue;
    }

    // 3. Recursive traversal for object properties, array items, and sub-schemas
    if (typeof value === 'object' && value !== null) {
      result[key] = sanitizeSchemaForGemini(value);
    } else {
      result[key] = value;
    }
  }

  return result;
}

/**
 * Converts a Zod schema to a Gemini-compatible OpenAPI response schema, using a WeakMap cache.
 *
 * @param schema The target Zod schema.
 * @returns A Gemini-compatible JSON schema object ready for GenerateContentConfig.responseSchema.
 */
export function getGeminiResponseSchema<T>(schema: ZodSchema<T>): Record<string, any> {
  if (schemaCache.has(schema)) {
    return schemaCache.get(schema)!;
  }

  // Native Zod 4 JSON Schema conversion (per EXP-02)
  const rawJsonSchema = z.toJSONSchema(schema) as Record<string, any>;

  // Sanitize raw JSON schema for Gemini OpenAPI compatibility
  const sanitizedSchema = sanitizeSchemaForGemini(rawJsonSchema);

  schemaCache.set(schema, sanitizedSchema);
  return sanitizedSchema;
}
