import type { WorkspaceRole } from "@/features/workspaces/types/workspace.types";

export const Permission = {
  WORKSPACE_UPDATE: "workspace:update",
  WORKSPACE_DELETE: "workspace:delete",
  MEMBER_LIST: "member:list",
  MEMBER_INVITE: "member:invite",
  MEMBER_ROLE_UPDATE: "member:role_update",
  MEMBER_REMOVE: "member:remove",
  PROJECT_CREATE: "project:create",
  PROJECT_READ: "project:read",
  PROJECT_UPDATE: "project:update",
  PROJECT_DELETE: "project:delete",
  PROJECT_ARCHIVE: "project:archive",
  TASK_CREATE: "task:create",
  TASK_READ: "task:read",
  TASK_UPDATE: "task:update",
  TASK_DELETE: "task:delete",
  TASK_ASSIGN: "task:assign",
  MILESTONE_CREATE: "milestone:create",
  MILESTONE_READ: "milestone:read",
  MILESTONE_UPDATE: "milestone:update",
  MILESTONE_DELETE: "milestone:delete",
  AI_COPILOT_QUERY: "ai:copilot_query",
  AI_ACTION_EXECUTE: "ai:action_execute",
  DASHBOARD_VIEW: "dashboard:view",
  SEARCH_EXECUTE: "search:execute",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
  OWNER: Object.values(Permission),
  ADMIN: [
    Permission.MEMBER_LIST,
    Permission.MEMBER_INVITE,
    Permission.MEMBER_ROLE_UPDATE,
    Permission.MEMBER_REMOVE,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_READ,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_DELETE,
    Permission.PROJECT_ARCHIVE,
    Permission.TASK_CREATE,
    Permission.TASK_READ,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.MILESTONE_CREATE,
    Permission.MILESTONE_READ,
    Permission.MILESTONE_UPDATE,
    Permission.MILESTONE_DELETE,
    Permission.AI_COPILOT_QUERY,
    Permission.AI_ACTION_EXECUTE,
    Permission.DASHBOARD_VIEW,
    Permission.SEARCH_EXECUTE,
  ],
  MEMBER: [
    Permission.MEMBER_LIST,
    Permission.PROJECT_CREATE,
    Permission.PROJECT_READ,
    Permission.PROJECT_UPDATE,
    Permission.PROJECT_ARCHIVE,
    Permission.TASK_CREATE,
    Permission.TASK_READ,
    Permission.TASK_UPDATE,
    Permission.TASK_DELETE,
    Permission.TASK_ASSIGN,
    Permission.MILESTONE_CREATE,
    Permission.MILESTONE_READ,
    Permission.MILESTONE_UPDATE,
    Permission.AI_COPILOT_QUERY,
    Permission.AI_ACTION_EXECUTE,
    Permission.DASHBOARD_VIEW,
    Permission.SEARCH_EXECUTE,
  ],
  VIEWER: [
    Permission.MEMBER_LIST,
    Permission.PROJECT_READ,
    Permission.TASK_READ,
    Permission.MILESTONE_READ,
    Permission.DASHBOARD_VIEW,
    Permission.SEARCH_EXECUTE,
  ],
};
