import { Document, Model, Schema, Types, model } from "mongoose";

import {
  MAX_RECOMMENDATION_EXPLANATION_LENGTH,
  MAX_RECOMMENDATION_RELATED_ENTITIES,
  MAX_RECOMMENDATION_SUGGESTED_NEXT_STEP_LENGTH,
  MAX_RECOMMENDATION_TITLE_LENGTH,
  PROJECT_RECOMMENDATION_SEVERITIES,
  PROJECT_RECOMMENDATION_STATUSES,
  PROJECT_SIGNAL_TYPES,
  RELATED_ENTITY_TYPES,
  ProjectRecommendationSeverity,
  ProjectRecommendationStatus,
  ProjectSignalType,
  RelatedEntityRef,
} from "@/constants/proactive-intelligence.js";

// ---------------------------------------------------------------------------
// Interface
// ---------------------------------------------------------------------------

/**
 * Canonical shape of a ProjectRecommendation document in MongoDB.
 *
 * Field rationale:
 * - `owner`             — Authenticated user owning the project. Required, immutable, server-controlled.
 * - `projectId`         — Target project. Required, immutable, server-controlled.
 * - `type`              — Restricted to canonical V1 signal types. Immutable.
 * - `severity`          — Deterministic signal severity (LOW, MEDIUM, HIGH, CRITICAL).
 * - `title`             — Deterministic title generated by signal engine.
 * - `explanation`       — Enriched natural language explanation (or deterministic fallback).
 *                         Default is empty string to support PENDING_ENRICHMENT without fake text.
 * - `suggestedNextStep` — Optional non-binding recommendation next step (max 300 chars).
 * - `facts`             — Structured deterministic facts dictionary.
 * - `relatedEntities`   — Array of embedded related entity references (max 20).
 * - `fingerprint`       — SHA-256 state fingerprint. Immutable.
 * - `claimToken`        — Cryptographic UUID establishing worker lease ownership. Internal metadata.
 * - `claimedAt`         — Timestamp when worker lease was claimed. Internal metadata.
 * - `status`            — Lifecycle status (PENDING_ENRICHMENT, ACTIVE, DISMISSED, ACTED_ON, EXPIRED).
 * - `dismissedAt`       — Timestamp when user manually dismissed recommendation.
 * - `actedOnAt`         — Optional lifecycle metadata timestamp when user acted on recommendation.
 * - `expiresAt`         — APPLICATION LIFECYCLE timestamp determining active/cooldown transition. NO TTL index.
 * - `purgeAt`           — PHYSICAL MONGO TTL CLEANUP timestamp. ONLY field with expireAfterSeconds: 0 index.
 * - `createdAt`         — Injected automatically by Mongoose timestamps.
 * - `updatedAt`         — Injected automatically by Mongoose timestamps.
 * - `__v`               — Mongoose version key for Optimistic Concurrency Control (OCC).
 */
export interface IProjectRecommendation {
  owner: Types.ObjectId;
  projectId: Types.ObjectId;
  type: ProjectSignalType;
  severity: ProjectRecommendationSeverity;

  title: string;
  explanation: string;
  suggestedNextStep?: string | null;

  facts: Record<string, unknown>;
  relatedEntities: RelatedEntityRef[];

  fingerprint: string;
  claimToken?: string | null;
  claimedAt?: Date | null;

  status: ProjectRecommendationStatus;
  dismissedAt?: Date | null;
  actedOnAt?: Date | null;

  expiresAt?: Date | null;
  purgeAt?: Date | null;

  createdAt: Date;
  updatedAt: Date;
  __v?: number;
}

export interface IProjectRecommendationDocument extends IProjectRecommendation, Document {}

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

const relatedEntitySchema = new Schema<RelatedEntityRef>(
  {
    type: {
      type: String,
      enum: RELATED_ENTITY_TYPES,
      required: true,
    },
    id: {
      type: String,
      required: true,
      trim: true,
    },
    label: {
      type: String,
      required: true,
      trim: true,
    },
  },
  { _id: false }
);

const projectRecommendationSchema = new Schema<IProjectRecommendationDocument>(
  {
    owner: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      immutable: true,
    },

    projectId: {
      type: Schema.Types.ObjectId,
      ref: "Project",
      required: true,
      immutable: true,
    },

    type: {
      type: String,
      enum: PROJECT_SIGNAL_TYPES,
      required: true,
      immutable: true,
    },

    severity: {
      type: String,
      enum: PROJECT_RECOMMENDATION_SEVERITIES,
      required: true,
    },

    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: MAX_RECOMMENDATION_TITLE_LENGTH,
    },

    explanation: {
      type: String,
      default: "",
      trim: true,
      maxlength: MAX_RECOMMENDATION_EXPLANATION_LENGTH,
    },

    suggestedNextStep: {
      type: String,
      default: null,
      trim: true,
      maxlength: MAX_RECOMMENDATION_SUGGESTED_NEXT_STEP_LENGTH,
    },

    facts: {
      type: Schema.Types.Mixed,
      default: {},
    },

    relatedEntities: {
      type: [relatedEntitySchema],
      default: [],
      validate: [
        {
          validator: function (val: RelatedEntityRef[]) {
            return Array.isArray(val) && val.length <= MAX_RECOMMENDATION_RELATED_ENTITIES;
          },
          message: `Related entities count cannot exceed ${MAX_RECOMMENDATION_RELATED_ENTITIES}.`,
        },
      ],
    },

    fingerprint: {
      type: String,
      required: true,
      trim: true,
      immutable: true,
    },

    claimToken: {
      type: String,
      default: null,
      trim: true,
    },

    claimedAt: {
      type: Date,
      default: null,
    },

    status: {
      type: String,
      enum: PROJECT_RECOMMENDATION_STATUSES,
      default: "PENDING_ENRICHMENT",
      required: true,
    },

    dismissedAt: {
      type: Date,
      default: null,
    },

    actedOnAt: {
      type: Date,
      default: null,
    },

    expiresAt: {
      type: Date,
      default: null,
    },

    purgeAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
    optimisticConcurrency: true,

    toJSON: {
      virtuals: true,
      transform(_doc, ret) {
        const {
          _id,
          __v,
          owner: _owner,
          projectId: rawProjectId,
          claimToken: _claimToken,
          claimedAt: _claimedAt,
          purgeAt: _purgeAt,
          ...safe
        } = ret as Record<string, unknown>;

        return {
          id: typeof _id === "object" && _id !== null ? _id.toString() : String(_id),
          projectId: typeof rawProjectId === "object" && rawProjectId !== null ? rawProjectId.toString() : String(rawProjectId),
          ...safe,
          version: typeof __v === "number" ? __v : 0,
        };
      },
    },
  }
);

// ---------------------------------------------------------------------------
// Indexes
// ---------------------------------------------------------------------------

/**
 * Index 1: Project-scoped active recommendation listing
 * Supports querying recommendations per project by status ordered by newest first.
 */
projectRecommendationSchema.index({ owner: 1, projectId: 1, status: 1, createdAt: -1 });

/**
 * Index 2: Dashboard recommendation listing across all user projects
 * Supports user-level active recommendation feed across workspace.
 */
projectRecommendationSchema.index({ owner: 1, status: 1, createdAt: -1 });

/**
 * Index 3: Partial unique index for active/pending fingerprint deduplication & atomic claims
 * Guarantees that at most ONE ACTIVE or PENDING_ENRICHMENT document exists for a given
 * { projectId, fingerprint } tuple. Excludes DISMISSED, ACTED_ON, EXPIRED from uniqueness.
 */
projectRecommendationSchema.index(
  { projectId: 1, fingerprint: 1 },
  {
    unique: true,
    partialFilterExpression: {
      status: { $in: ["ACTIVE", "PENDING_ENRICHMENT"] },
    },
  }
);

/**
 * Index 4: Physical MongoDB TTL index for retention policy cleanup
 * CRITICAL: purgeAt is the ONLY field with a TTL index. expiresAt has NO TTL INDEX.
 */
projectRecommendationSchema.index({ purgeAt: 1 }, { expireAfterSeconds: 0 });

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

const ProjectRecommendation: Model<IProjectRecommendationDocument> =
  model<IProjectRecommendationDocument>("ProjectRecommendation", projectRecommendationSchema);

export default ProjectRecommendation;
