import { describe, it, before, after } from "node:test";
import assert from "node:assert";
import mongoose from "mongoose";
import { setupTestDatabase, teardownTestDatabase } from "./test-db.js";
import { createProject } from "@/services/project.service.js";
import { createTask, getTaskById } from "@/services/task.service.js";
import { generateLabelsForTask } from "@/services/task-ai.service.js";
import { aiService } from "@/ai/ai.service.js";
import { promptRegistry } from "@/ai/prompts/registry/prompt.registry.js";
import { taskAutoLabelPrompt } from "@/ai/prompts/definitions/task-labels.prompt.js";
import User from "@/models/user.model.js";

describe("Task AI Service - Label Generation", () => {
  let userId: string;
  let projectId: string;

  before(async () => {
    await setupTestDatabase();
    const user = await User.create({
      username: "ai_test_user", name: "AI Test User",
      email: "ai-label-test@example.com",
      password: "password123",
    });
    userId = user._id.toString();

    const project = await createProject(userId, { 
      name: "AI Test Project",
      description: "A project for testing AI labels",
      emoji: "🚀",
      color: "blue"
    });
    projectId = project._id.toString();

    try {
      promptRegistry.register(taskAutoLabelPrompt);
    } catch (e) {
      // ignore if already registered
    }
  });

  after(async () => {
    await teardownTestDatabase();
  });

  it("should successfully generate and persist normalized labels from AI", async () => {
    const task = await createTask(userId, { projectId: projectId as any, title: "Implement JWT" });

    const originalGenerate = aiService.generateStructuredData.bind(aiService);
    aiService.generateStructuredData = async () => ({
      data: { labels: [" Backend ", "auth", "SECURITY  "] },
      metadata: { executionId: '123', provider: 'test', model: 'test', durationMs: 100, promptName: 'task-auto-label', promptVersion: '1.0' } } as any);

    try {
      const updatedTask = await generateLabelsForTask(task._id.toString(), userId);
      assert.strictEqual(updatedTask.labels.length, 3);
      assert.strictEqual(updatedTask.labels[0], "backend");
      assert.strictEqual(updatedTask.labels[1], "auth");
      assert.strictEqual(updatedTask.labels[2], "security");
    } finally {
      aiService.generateStructuredData = originalGenerate;
    }
  });

  it("should deduplicate labels generated by AI", async () => {
    const task = await createTask(userId, { projectId: projectId as any, title: "Fix UI" });

    const originalGenerate = aiService.generateStructuredData.bind(aiService);
    aiService.generateStructuredData = async () => ({
      data: { labels: ["ui", " UI ", "frontend", "frontend"] },
      metadata: { executionId: '123', provider: 'test', model: 'test', durationMs: 100, promptName: 'task-auto-label', promptVersion: '1.0' } } as any);

    try {
      const updatedTask = await generateLabelsForTask(task._id.toString(), userId);
      assert.strictEqual(updatedTask.labels.length, 2);
      assert.strictEqual(updatedTask.labels[0], "ui");
      assert.strictEqual(updatedTask.labels[1], "frontend");
    } finally {
      aiService.generateStructuredData = originalGenerate;
    }
  });

  it("should merge with existing labels and deduplicate", async () => {
    const task = await createTask(userId, { projectId: projectId as any, title: "Add caching", labels: ["backend", "redis"] });

    const originalGenerate = aiService.generateStructuredData.bind(aiService);
    aiService.generateStructuredData = async () => ({
      data: { labels: ["Backend", "Performance", "Redis", "cache"] },
      metadata: { executionId: '123', provider: 'test', model: 'test', durationMs: 100, promptName: 'task-auto-label', promptVersion: '1.0' } } as any);

    try {
      const updatedTask = await generateLabelsForTask(task._id.toString(), userId);
      assert.strictEqual(updatedTask.labels.length, 4);
      // Existing labels kept exactly as they were (case-wise)
      assert.strictEqual(updatedTask.labels[0], "backend");
      assert.strictEqual(updatedTask.labels[1], "redis");
      // New labels normalized and appended
      assert.strictEqual(updatedTask.labels[2], "performance");
      assert.strictEqual(updatedTask.labels[3], "cache");
    } finally {
      aiService.generateStructuredData = originalGenerate;
    }
  });

  it("should cap the total number of labels to 10", async () => {
    const task = await createTask(userId, { 
      projectId, 
      title: "Huge task", 
      labels: ["l1", "l2", "l3", "l4", "l5", "l6", "l7"] 
    });

    const originalGenerate = aiService.generateStructuredData.bind(aiService);
    aiService.generateStructuredData = async () => ({
      data: { labels: ["n1", "n2", "n3", "n4", "n5"] },
      metadata: { executionId: '123', provider: 'test', model: 'test', durationMs: 100, promptName: 'task-auto-label', promptVersion: '1.0' } } as any);

    try {
      const updatedTask = await generateLabelsForTask(task._id.toString(), userId);
      assert.strictEqual(updatedTask.labels.length, 10);
      assert.strictEqual(updatedTask.labels[9], "n3");
      assert.strictEqual(updatedTask.labels.includes("n4"), false);
    } finally {
      aiService.generateStructuredData = originalGenerate;
    }
  });
});
