import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";

import { aiApi } from "@/features/ai/services/ai.api";
import { projectKeys } from "@/features/projects/hooks/useProjects";
import { activityKeys } from "@/features/activity/hooks/activity.keys";

/**
 * Mutation hook for generating an AI summary for a project.
 *
 * Cache Invalidation on Success:
 * - `projectKeys.detail(projectId)`: Refreshes the project entity to populate updated `aiSummary`.
 * - `projectKeys.lists()`: Invalidates project list queries to reflect summary updates.
 * - `activityKeys.all`: Refreshes activity log entries generated by backend summary creation.
 */
export function useGenerateProjectSummary(projectId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: () => aiApi.generateSummary(projectId),

    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: projectKeys.detail(projectId) });
      queryClient.invalidateQueries({ queryKey: projectKeys.lists() });
      queryClient.invalidateQueries({ queryKey: activityKeys.all });

      toast.success("Project summary generated successfully.");
    },
  });
}
