import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";

import { aiApi } from "@/features/ai/services/ai.api";
import type { GenerateTasksDto } from "@/features/ai/types/ai.types";
import { taskKeys } from "@/features/tasks/hooks/useTasks";
import { projectKeys } from "@/features/projects/hooks/useProjects";
import { dashboardKeys } from "@/features/dashboard/hooks/dashboard.keys";
import { activityKeys } from "@/features/activity/hooks/activity.keys";

/**
 * Mutation hook for generating tasks using AI for a given project.
 *
 * Cache Invalidation on Success:
 * - `taskKeys.lists()`: Makes generated tasks immediately visible in task lists.
 * - `projectKeys.summary(projectId)`: Refreshes total/remaining task metrics for the project.
 * - `dashboardKeys.overview()`: Refreshes overview analytics.
 * - `activityKeys.all`: Refreshes activity log entries generated by backend task creation.
 */
export function useGenerateTasks(projectId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: GenerateTasksDto) => aiApi.generateTasks(projectId, data),

    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: taskKeys.lists() });
      queryClient.invalidateQueries({ queryKey: projectKeys.summary(projectId) });
      queryClient.invalidateQueries({ queryKey: dashboardKeys.overview() });
      queryClient.invalidateQueries({ queryKey: activityKeys.all });

      const count = data.items.length;
      toast.success(
        count === 1
          ? "1 task generated successfully."
          : `${count} tasks generated successfully.`,
      );
    },
  });
}
