import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";

import { aiApi } from "@/features/ai/services/ai.api";
import { taskKeys } from "@/features/tasks/hooks/useTasks";
import { activityKeys } from "@/features/activity/hooks/activity.keys";

/**
 * Mutation hook for auto-generating AI labels for a task.
 *
 * Cache Invalidation on Success:
 * - `taskKeys.detail(taskId)`: Refreshes the task detail view with newly assigned labels.
 * - `taskKeys.lists()`: Refreshes task list queries to update label tags across tables and cards.
 * - `activityKeys.all`: Refreshes activity log entries generated by backend label update.
 */
export function useGenerateTaskLabels(taskId: string) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: () => aiApi.generateLabels(taskId),

    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: taskKeys.detail(taskId) });
      queryClient.invalidateQueries({ queryKey: taskKeys.lists() });
      queryClient.invalidateQueries({ queryKey: activityKeys.all });

      toast.success("Labels generated and applied successfully.");
    },
  });
}
